services:
  app:
    container_name: atask_wallet_api
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: /bin/sh -c "/wait
      && bundle install
      && rm -f tmp/pids/server.pid
      && bundle exec rails s -b 0.0.0.0"
    ports:
      - 4000:3000
    stdin_open: true
    tty: true
    env_file: .env
    environment:
      WAIT_HOSTS: ${DB_HOST}:${DB_PORT}
    restart: always

networks:
  default:
    name: dijeka_default
    external: true
